// <auto-generated />
using System;
using AnimateDataStructure.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimateDataStructure.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250912124831_AddNodeFieldAddOther3")]
    partial class AddNodeFieldAddOther3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.DataStructureEntities.AvlTree", b =>
                {
                    b.Property<int>("AvlTreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvlTreeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TempGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AvlTreeId");

                    b.HasIndex("UserId");

                    b.ToTable("AvlTrees");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.DataStructureEntities.BinarySearchTree", b =>
                {
                    b.Property<int>("BinarySearchTreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BinarySearchTreeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TempGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BinarySearchTreeId");

                    b.HasIndex("UserId");

                    b.ToTable("BinarySearchTrees");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.DataStructureEntities.MaxHeap", b =>
                {
                    b.Property<int>("MaxHeapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaxHeapId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TempGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaxHeapId");

                    b.HasIndex("UserId");

                    b.ToTable("MaxHeaps");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.DataStructureEntities.MinHeap", b =>
                {
                    b.Property<int>("MinHeapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MinHeapId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TempGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MinHeapId");

                    b.HasIndex("UserId");

                    b.ToTable("MinHeaps");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.DataStructureEntities.RedBlackTree", b =>
                {
                    b.Property<int>("RedBlackTreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RedBlackTreeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsNodeRedColor")
                        .HasColumnType("bit");

                    b.Property<Guid>("TempGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RedBlackTreeId");

                    b.HasIndex("UserId");

                    b.ToTable("RedBlackTrees");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.NodeEntities.NodeAvlTree", b =>
                {
                    b.Property<int>("NodeAvlTreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NodeAvlTreeId"));

                    b.Property<int>("AvlTreeId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("NodeAvlTreeId");

                    b.HasIndex("AvlTreeId");

                    b.ToTable("NodeAvlTrees");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.NodeEntities.NodeBinarySearchTree", b =>
                {
                    b.Property<int>("NodeBinarySearchTreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NodeBinarySearchTreeId"));

                    b.Property<int>("BinarySearchTreeId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("NodeBinarySearchTreeId");

                    b.HasIndex("BinarySearchTreeId");

                    b.ToTable("NodeBinarySearchTrees");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.NodeEntities.NodeMaxHeap", b =>
                {
                    b.Property<int>("NodeMaxHeapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NodeMaxHeapId"));

                    b.Property<int>("MaxHeapId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("NodeMaxHeapId");

                    b.HasIndex("MaxHeapId");

                    b.ToTable("NodeMaxHeaps");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.NodeEntities.NodeMinHeap", b =>
                {
                    b.Property<int>("NodeMinHeapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NodeMinHeapId"));

                    b.Property<int>("MinHeapId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("NodeMinHeapId");

                    b.HasIndex("MinHeapId");

                    b.ToTable("NodeMinHeaps");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.NodeEntities.NodeRedBlackTree", b =>
                {
                    b.Property<int>("NodeRedBlackTreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NodeRedBlackTreeId"));

                    b.Property<bool>("IsRedNode")
                        .HasColumnType("bit");

                    b.Property<int>("ReadBlackTreeId")
                        .HasColumnType("int");

                    b.Property<int>("RedBlackTreeId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("NodeRedBlackTreeId");

                    b.HasIndex("RedBlackTreeId");

                    b.ToTable("NodeRedBlackTrees");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.DataStructureEntities.AvlTree", b =>
                {
                    b.HasOne("AnimateDataStructure.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.DataStructureEntities.BinarySearchTree", b =>
                {
                    b.HasOne("AnimateDataStructure.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.DataStructureEntities.MaxHeap", b =>
                {
                    b.HasOne("AnimateDataStructure.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.DataStructureEntities.MinHeap", b =>
                {
                    b.HasOne("AnimateDataStructure.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.DataStructureEntities.RedBlackTree", b =>
                {
                    b.HasOne("AnimateDataStructure.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.NodeEntities.NodeAvlTree", b =>
                {
                    b.HasOne("AnimateDataStructure.Core.Entities.DataStructureEntities.AvlTree", "AvlTree")
                        .WithMany("Nodes")
                        .HasForeignKey("AvlTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvlTree");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.NodeEntities.NodeBinarySearchTree", b =>
                {
                    b.HasOne("AnimateDataStructure.Core.Entities.DataStructureEntities.BinarySearchTree", "BinarySearchTree")
                        .WithMany("Nodes")
                        .HasForeignKey("BinarySearchTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BinarySearchTree");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.NodeEntities.NodeMaxHeap", b =>
                {
                    b.HasOne("AnimateDataStructure.Core.Entities.DataStructureEntities.MaxHeap", "MaxHeap")
                        .WithMany("Nodes")
                        .HasForeignKey("MaxHeapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaxHeap");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.NodeEntities.NodeMinHeap", b =>
                {
                    b.HasOne("AnimateDataStructure.Core.Entities.DataStructureEntities.MinHeap", "MinHeap")
                        .WithMany("Nodes")
                        .HasForeignKey("MinHeapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MinHeap");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.NodeEntities.NodeRedBlackTree", b =>
                {
                    b.HasOne("AnimateDataStructure.Core.Entities.DataStructureEntities.RedBlackTree", "RedBlackTree")
                        .WithMany("Nodes")
                        .HasForeignKey("RedBlackTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RedBlackTree");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AnimateDataStructure.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AnimateDataStructure.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimateDataStructure.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AnimateDataStructure.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.DataStructureEntities.AvlTree", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.DataStructureEntities.BinarySearchTree", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.DataStructureEntities.MaxHeap", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.DataStructureEntities.MinHeap", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("AnimateDataStructure.Core.Entities.DataStructureEntities.RedBlackTree", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
